"use client";

import Image from "next/image";
import { useEffect, useId, useRef, useState, type FormEvent } from "react";
import { orders, products } from "@/data/catalog";
import { formatCurrency, formatDate } from "@/lib/format";
import { Icon } from "../ui/Icon";
import { StatusBadge } from "../ui/StatusBadge";
import { useToast } from "../ui/ToastProvider";

type Entity = "products" | "categories" | "orders";
type ModalMode = "add-product" | "edit-product" | "delete-product" | "add-category" | "edit-category" | "delete-category" | "update-order" | "delete-order";

const config = {
  products: { title: "Produk", description: "Kelola katalog, harga, stok, dan status publikasi produk.", search: "Cari nama atau slug produk...", filterLabel: "Filter kategori produk", filters: ["Semua kategori", "Alat Tulis", "Dekorasi", "Perawatan"], headers: ["Produk", "Kategori", "Harga", "Stok", "Status", "Aksi"], result: `${products.length} produk`, action: "Tambah Produk", addMode: "add-product" as ModalMode },
  categories: { title: "Kategori", description: "Atur struktur kategori agar katalog tetap rapi dan mudah ditemukan.", search: "Cari nama atau slug kategori...", filterLabel: "Filter status kategori", filters: ["Semua status", "Aktif", "Nonaktif"], headers: ["Kategori", "Slug", "Jumlah Produk", "Dibuat", "Aksi"], result: "3 kategori", action: "Tambah Kategori", addMode: "add-category" as ModalMode },
  orders: { title: "Pesanan", description: "Pantau pembayaran, pemrosesan, dan pengiriman pesanan pelanggan.", search: "Cari nomor order atau pelanggan...", filterLabel: "Filter status pesanan", filters: ["Semua status", "Menunggu pembayaran", "Diproses", "Dikirim", "Selesai", "Gagal"], headers: ["Order", "Customer", "Tanggal", "Total", "Status", "Aksi"], result: `${orders.length} pesanan`, action: null, addMode: null }
};

function ActionButtons({ editMode, deleteMode, label, open }: { editMode: ModalMode; deleteMode: ModalMode; label: string; open: (mode: ModalMode, target: string) => void }) {
  return <div className="flex gap-2"><button type="button" className="rounded-lg border border-black/15 p-2 hover:bg-canvas-gray" onClick={() => open(editMode, label)} aria-label={`Edit ${label}`}><Icon name="edit" className="h-4 w-4" /></button><button type="button" className="rounded-lg border border-status-error/25 p-2 text-status-error hover:bg-status-error hover:text-white" onClick={() => open(deleteMode, label)} aria-label={`Hapus ${label}`}><Icon name="trash" className="h-4 w-4" /></button></div>;
}

function TableRows({ entity, open }: { entity: Entity; open: (mode: ModalMode, target: string) => void }) {
  if (entity === "products") return <>{products.map((product) => <tr key={product.id} className="border-b border-black/8 last:border-0"><td className="px-4 py-4"><div className="flex min-w-48 items-center gap-3"><Image src={product.imageUrl} alt={product.imageAlt} width={52} height={52} quality={80} className="h-12 w-12 rounded-lg object-cover" /><div><p className="font-bold text-ink-black">{product.name}</p><p className="text-xs">{product.slug}</p></div></div></td><td className="px-4 py-4 text-sm">{product.category}</td><td className="px-4 py-4 text-sm font-semibold text-ink-black">{formatCurrency(product.price)}</td><td className="px-4 py-4 text-sm">{product.stock}</td><td className="px-4 py-4"><span className="rounded-full bg-status-success/10 px-3 py-1 text-xs font-bold text-status-success">Aktif</span></td><td className="px-4 py-4"><ActionButtons editMode="edit-product" deleteMode="delete-product" label={product.name} open={open} /></td></tr>)}</>;
  if (entity === "categories") return <>{["Alat Tulis", "Dekorasi", "Perawatan"].map((category) => <tr key={category} className="border-b border-black/8 last:border-0"><td className="px-4 py-5 font-bold text-ink-black">{category}</td><td className="px-4 py-5 text-sm">{category.toLocaleLowerCase("id-ID").replace(" ", "-")}</td><td className="px-4 py-5 text-sm">{products.filter((product) => product.category === category).length}</td><td className="px-4 py-5 text-sm">1 Agustus 2026</td><td className="px-4 py-5"><ActionButtons editMode="edit-category" deleteMode="delete-category" label={category} open={open} /></td></tr>)}</>;
  return <>{orders.map((order) => { const total = order.items.reduce((sum, item) => sum + item.price * item.quantity, 0); return <tr key={order.id} className="border-b border-black/8 last:border-0"><td className="px-4 py-4 font-bold text-ink-black">{order.id}</td><td className="px-4 py-4 text-sm">Pelanggan Demo</td><td className="px-4 py-4 text-sm">{formatDate(order.date)}</td><td className="px-4 py-4 text-sm font-semibold text-ink-black">{formatCurrency(total)}</td><td className="px-4 py-4"><StatusBadge status={order.status} /></td><td className="px-4 py-4"><ActionButtons editMode="update-order" deleteMode="delete-order" label={order.id} open={open} /></td></tr>; })}</>;
}

function Pagination() {
  return <nav className="flex flex-wrap items-center justify-between gap-4 border-t border-black/10 px-5 py-4" aria-label="Pagination tabel"><p className="text-sm">Halaman <strong className="text-ink-black">1</strong> dari 4</p><div className="flex items-center gap-2"><button type="button" className="grid h-10 w-10 place-items-center rounded-lg border border-black/15 text-body-gray opacity-40" disabled aria-label="Halaman sebelumnya"><Icon name="chevron" className="h-4 w-4 rotate-180" /></button><button type="button" className="grid h-10 w-10 place-items-center rounded-lg bg-ink-black text-sm font-bold text-white" aria-current="page" aria-label="Halaman 1">1</button><button type="button" className="grid h-10 w-10 place-items-center rounded-lg border border-black/15 bg-white text-sm font-bold text-ink-black" aria-label="Halaman 2">2</button><button type="button" className="hidden h-10 w-10 place-items-center rounded-lg border border-black/15 bg-white text-sm font-bold text-ink-black sm:grid" aria-label="Halaman 3">3</button><span className="px-1" aria-hidden="true">…</span><button type="button" className="grid h-10 w-10 place-items-center rounded-lg border border-black/15 bg-white text-sm font-bold text-ink-black" aria-label="Halaman berikutnya"><Icon name="chevron" className="h-4 w-4" /></button></div></nav>;
}

function ProductFields() { return <><div><label className="form-label" htmlFor="modal-name">Nama produk</label><input id="modal-name" className="form-input" defaultValue="Notebook Harian" required /></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="form-label" htmlFor="modal-category">Kategori</label><select id="modal-category" className="form-input"><option>Alat Tulis</option><option>Dekorasi</option><option>Perawatan</option></select></div><div><label className="form-label" htmlFor="modal-price">Harga</label><input id="modal-price" type="number" className="form-input" defaultValue="89000" min="0" required /></div></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="form-label" htmlFor="modal-stock">Stok</label><input id="modal-stock" type="number" className="form-input" defaultValue="24" min="0" required /></div><div><label className="form-label" htmlFor="modal-status">Status</label><select id="modal-status" className="form-input"><option>Aktif</option><option>Nonaktif</option></select></div></div><div><label className="form-label" htmlFor="modal-description">Deskripsi</label><textarea id="modal-description" className="form-input min-h-24" defaultValue="Produk kreatif pilihan KreasiKita." /></div></>; }
function CategoryFields() { return <><div><label className="form-label" htmlFor="category-name">Nama kategori</label><input id="category-name" className="form-input" defaultValue="Dekorasi" required /></div><div><label className="form-label" htmlFor="category-slug">Slug</label><input id="category-slug" className="form-input" defaultValue="dekorasi" required /></div></>; }
function OrderFields({ target }: { target: string }) { return <><div className="rounded-xl bg-canvas-gray p-4"><p className="text-sm">Order</p><strong className="text-ink-black">{target || "KK-2026-0812"}</strong></div><div><label className="form-label" htmlFor="order-status">Status pesanan</label><select id="order-status" className="form-input"><option>PAID</option><option>PROCESSING</option><option>SHIPPED</option><option>COMPLETED</option></select></div><p className="text-sm leading-6">Status hanya dapat bergerak maju sesuai state machine order. Validasi final wajib dilakukan kembali di server.</p></>; }

function AdminModal({ mode, target, close }: { mode: ModalMode; target: string; close: () => void }) {
  const { showToast } = useToast();
  const closeButton = useRef<HTMLButtonElement>(null);
  const titleId = useId();
  useEffect(() => { closeButton.current?.focus(); const escape = (event: KeyboardEvent) => { if (event.key === "Escape") close(); }; document.addEventListener("keydown", escape); return () => document.removeEventListener("keydown", escape); }, [close]);
  const deleteMode = mode.startsWith("delete-");
  const title = mode === "delete-product" ? "Nonaktifkan Produk" : mode === "delete-category" ? "Hapus Kategori" : mode === "delete-order" ? "Arsipkan Pesanan" : mode === "add-category" ? "Tambah Kategori" : mode === "edit-category" ? "Edit Kategori" : mode === "update-order" ? "Update Pesanan" : mode === "edit-product" ? "Edit Produk" : "Tambah Produk";
  const deleteCopy = mode === "delete-category" ? ["Kategori akan dinonaktifkan.", "Produk yang terhubung tidak ikut dihapus. Backend wajib menolak penghapusan permanen selama relasi masih digunakan."] : mode === "delete-order" ? ["Pesanan akan diarsipkan.", "Riwayat transaksi tidak dihapus permanen agar audit pembayaran dan stok tetap utuh."] : ["Produk akan dinonaktifkan.", "Data tidak dihapus permanen karena mungkin telah terikat pada order."];
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); close(); showToast("Perubahan demo tervalidasi. Penyimpanan menunggu API admin Next.js pada tahap backend."); };
  return <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 p-4" onMouseDown={(event) => { if (event.target === event.currentTarget) close(); }} role="dialog" aria-modal="true" aria-labelledby={titleId}><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between gap-4 border-b-2 border-brand-yellow pb-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em]">Form Admin</p><h2 id={titleId} className="font-display text-3xl font-bold text-ink-black">{title}</h2>{target && <p className="mt-1 text-sm">{target}</p>}</div><button ref={closeButton} type="button" className="rounded-full p-2 hover:bg-canvas-gray" onClick={close} aria-label="Tutup modal"><Icon name="close" /></button></div><form className="mt-6 space-y-5" onSubmit={submit}>{deleteMode ? <div className="rounded-xl border border-status-error/20 bg-status-error/5 p-5"><p className="font-bold text-status-error">{deleteCopy[0]}</p><p className="mt-2 text-sm leading-6">{deleteCopy[1]}</p></div> : mode.includes("category") ? <CategoryFields /> : mode === "update-order" ? <OrderFields target={target} /> : <ProductFields />}<div className="flex flex-col-reverse gap-3 pt-2 sm:flex-row sm:justify-end"><button type="button" className="btn-secondary px-5 py-2.5" onClick={close}>Batal</button><button type="submit" className="btn-primary px-5 py-2.5">{deleteMode ? "Konfirmasi" : "Simpan"}</button></div></form></div></div>;
}

export function AdminDataPage({ entity }: { entity: Entity }) {
  const settings = config[entity];
  const [modal, setModal] = useState<{ mode: ModalMode; target: string } | null>(null);
  const searchId = `${entity}-search`;
  const open = (mode: ModalMode, target = "") => setModal({ mode, target });
  return <><section className="rounded-2xl bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-black/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em] text-body-gray">Kelola Data</p><h2 className="font-display text-3xl font-bold text-ink-black">{settings.title}</h2><p className="mt-1 max-w-2xl text-sm leading-6">{settings.description}</p></div>{settings.action && settings.addMode && <button type="button" className="btn-primary shrink-0 px-5 py-2.5 text-sm" onClick={() => open(settings.addMode!)}><Icon name="plus" className="h-4 w-4" /> {settings.action}</button>}</div><div className="grid gap-3 border-b border-black/10 p-5 md:grid-cols-[minmax(0,1fr)_15rem]"><div><label className="sr-only" htmlFor={searchId}>Cari {settings.title.toLocaleLowerCase("id-ID")}</label><div className="relative"><input id={searchId} type="search" className="form-input pl-11" placeholder={settings.search} /><Icon name="search" className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-body-gray" /></div></div><div><label className="sr-only" htmlFor={`${searchId}-filter`}>{settings.filterLabel}</label><select id={`${searchId}-filter`} className="form-input" aria-label={settings.filterLabel}>{settings.filters.map((filter) => <option key={filter}>{filter}</option>)}</select></div></div><div className="flex items-center justify-between gap-4 px-5 py-4"><p className="text-sm"><strong className="text-ink-black">{settings.result}</strong> ditampilkan</p><p className="text-xs text-body-gray">Tampilan demonstrasi</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-ink-black text-xs uppercase tracking-[0.12em] text-white"><tr>{settings.headers.map((header) => <th key={header} scope="col" className="px-4 py-3 font-semibold">{header}</th>)}</tr></thead><tbody><TableRows entity={entity} open={open} /></tbody></table></div><Pagination /></section>{modal && <AdminModal mode={modal.mode} target={modal.target} close={() => setModal(null)} />}</>;
}
