"use client";

import { useState, type FormEvent } from "react";
import { Icon } from "../ui/Icon";
import { useToast } from "../ui/ToastProvider";

interface Settings { storeName: string; email: string; phone: string | null; address: string | null; shippingCost: number }
export function AdminSettingsForm({ settings }: { settings: Settings }) {
  const { showToast } = useToast(); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!event.currentTarget.reportValidity()) return; setSaving(true); setError(""); const values = new FormData(event.currentTarget); const response = await fetch("/api/admin/settings", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ storeName: values.get("storeName"), email: values.get("email"), phone: values.get("phone"), address: values.get("address"), shippingCost: values.get("shippingCost") }) }); const result = await response.json() as { error?: string }; setSaving(false); if (!response.ok) return setError(result.error ?? "Pengaturan belum dapat disimpan."); showToast("Pengaturan toko berhasil disimpan."); };
  return <form className="space-y-7" onSubmit={submit}><section className="admin-card sm:p-8"><div className="flex items-center gap-3 border-b border-black/10 pb-5"><span className="grid h-11 w-11 place-items-center rounded-xl bg-brand-yellow"><Icon name="store" /></span><div><h3 className="font-display text-2xl font-bold text-ink-black">Informasi Toko</h3><p className="text-sm">Digunakan storefront dan proses checkout.</p></div></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><label className="form-label" htmlFor="store-name">Nama toko</label><input id="store-name" name="storeName" className="form-input" defaultValue={settings.storeName} required /></div><div><label className="form-label" htmlFor="store-email">Email kontak</label><input id="store-email" name="email" type="email" className="form-input" defaultValue={settings.email} required /></div><div><label className="form-label" htmlFor="store-phone">Telepon</label><input id="store-phone" name="phone" className="form-input" defaultValue={settings.phone ?? ""} /></div><div><label className="form-label" htmlFor="shipping-cost">Ongkos kirim</label><input id="shipping-cost" name="shippingCost" type="number" min="0" className="form-input" defaultValue={settings.shippingCost} required /></div><div className="sm:col-span-2"><label className="form-label" htmlFor="store-address">Alamat toko</label><textarea id="store-address" name="address" className="form-input min-h-28" defaultValue={settings.address ?? ""} /></div></div>{error && <p className="form-error mt-5" role="alert">{error}</p>}</section><div className="sticky bottom-4 flex justify-end rounded-2xl border border-black/10 bg-white/95 p-4 shadow-xl"><button disabled={saving} className="btn-primary px-5 py-2.5 disabled:opacity-60">{saving ? "Menyimpan…" : "Simpan Pengaturan"}</button></div></form>;
}
