"use client";

import Image from "next/image";
import { useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import type { OrderStatus } from "@/types";
import { formatCurrency, formatDate } from "@/lib/format";
import { Icon } from "../ui/Icon";
import { StatusBadge } from "../ui/StatusBadge";
import { useToast } from "../ui/ToastProvider";

type ProductImageInput = { url: string; alt: string; publicId?: string; photographer?: string; photoPage?: string };
type ProductRow = { id: string; name: string; slug: string; category: string; categoryId: string; description: string; price: number; stock: number; badge: string; keywords: string[]; featured: boolean; isActive: boolean; imageUrl: string; imageAlt: string; images: ProductImageInput[] };
type CategoryRow = { id: string; name: string; slug: string; isActive: boolean; productCount: number; createdAt: string };
type OrderRow = { id: string; customer: string; date: string; total: number; status: OrderStatus };
type CategoryOption = { id: string; name: string };
type Props = { entity: "products"; rows: ProductRow[]; categories: CategoryOption[] } | { entity: "categories"; rows: CategoryRow[] } | { entity: "orders"; rows: OrderRow[] };
type Editor = { kind: "product"; row?: ProductRow } | { kind: "category"; row?: CategoryRow };

const copy = {
  products: { title: "Produk", description: "Kelola katalog, harga, stok, dan status publikasi produk.", search: "Cari nama atau slug produk..." },
  categories: { title: "Kategori", description: "Atur struktur kategori agar katalog tetap rapi dan mudah ditemukan.", search: "Cari nama atau slug kategori..." },
  orders: { title: "Pesanan", description: "Pantau pembayaran, pemrosesan, dan pengiriman pesanan pelanggan.", search: "Cari nomor order atau pelanggan..." },
};

export function AdminDatabaseTable(props: Props) {
  const router = useRouter(); const { showToast } = useToast();
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("Semua"); const [page, setPage] = useState(1);
  const [busy, setBusy] = useState(""); const [editor, setEditor] = useState<Editor | null>(null); const [formError, setFormError] = useState("");
  const settings = copy[props.entity];
  const filters = props.entity === "orders" ? ["Semua", "PENDING", "PAID", "PROCESSING", "SHIPPED", "COMPLETED", "FAILED", "EXPIRED", "CANCELLED"] : ["Semua", "Aktif", "Nonaktif"];
  const filtered = useMemo(() => props.rows.filter((row) => {
    const haystack = "customer" in row ? `${row.id} ${row.customer}` : `${row.name} ${row.slug}`;
    return haystack.toLocaleLowerCase("id-ID").includes(query.trim().toLocaleLowerCase("id-ID")) && (filter === "Semua" || ("status" in row ? row.status === filter : filter === "Aktif" ? row.isActive : !row.isActive));
  }), [filter, props, query]);
  const pageSize = 8; const totalPages = Math.max(1, Math.ceil(filtered.length / pageSize)); const safePage = Math.min(page, totalPages); const rows = filtered.slice((safePage - 1) * pageSize, safePage * pageSize);

  const request = async (url: string, method: string, body?: unknown) => { const response = await fetch(url, { method, headers: body ? { "content-type": "application/json" } : undefined, body: body ? JSON.stringify(body) : undefined }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error ?? "Permintaan gagal."); };
  const remove = async (id: string) => { if (!window.confirm(props.entity === "orders" ? "Arsipkan pesanan ini? Riwayat audit tetap disimpan." : "Lanjutkan tindakan ini?")) return; setBusy(id); try { await request(`/api/${props.entity}/${encodeURIComponent(id)}`, "DELETE"); showToast(props.entity === "orders" ? "Pesanan berhasil diarsipkan." : "Data berhasil diperbarui."); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Tindakan gagal."); } finally { setBusy(""); } };
  const updateStatus = async (id: string, status: string) => { setBusy(id); try { await request(`/api/orders/${encodeURIComponent(id)}/status`, "PUT", { status }); showToast("Status pesanan berhasil diperbarui."); router.refresh(); } catch (error) { showToast(error instanceof Error ? error.message : "Status gagal diperbarui."); } finally { setBusy(""); } };
  const saveEditor = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity() || !editor) return; setBusy("editor"); setFormError(""); const values = new FormData(form);
    try {
      if (editor.kind === "category") await request(editor.row ? `/api/categories/${editor.row.id}` : "/api/categories", editor.row ? "PUT" : "POST", { name: values.get("name"), isActive: values.get("isActive") === "true" });
      else {
        const imageUrl = String(values.get("imageUrl") ?? ""); const oldImage = editor.row?.images.find((image) => image.url === imageUrl);
        const body = { name: values.get("name"), categoryId: values.get("categoryId"), description: values.get("description"), price: values.get("price"), stock: values.get("stock"), badge: values.get("badge"), keywords: String(values.get("keywords") ?? "").split(",").map((value) => value.trim()).filter(Boolean), featured: values.get("featured") === "on", isActive: values.get("isActive") === "true", images: [{ ...(oldImage ?? {}), url: imageUrl, alt: values.get("imageAlt") }] };
        await request(editor.row ? `/api/products/${editor.row.id}` : "/api/products", editor.row ? "PUT" : "POST", body);
      }
      showToast(`${editor.row ? "Perubahan" : "Data baru"} berhasil disimpan.`); setEditor(null); router.refresh();
    } catch (error) { setFormError(error instanceof Error ? error.message : "Data belum dapat disimpan."); } finally { setBusy(""); }
  };

  const headers = props.entity === "products" ? ["Produk", "Kategori", "Harga", "Stok", "Status", "Aksi"] : props.entity === "categories" ? ["Kategori", "Slug", "Jumlah Produk", "Dibuat", "Status", "Aksi"] : ["Order", "Customer", "Tanggal", "Total", "Status", "Aksi"];
  return <><section className="rounded-2xl bg-white shadow-sm"><div className="flex flex-col gap-4 border-b border-black/10 p-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs font-bold uppercase tracking-[0.16em]">Kelola Data</p><h2 className="font-display text-3xl font-bold text-ink-black">{settings.title}</h2><p className="mt-1 text-sm">{settings.description}</p></div>{props.entity !== "orders" && <button className="btn-primary shrink-0 px-5 py-2.5 text-sm" onClick={() => setEditor(props.entity === "products" ? { kind: "product" } : { kind: "category" })}><Icon name="plus" className="h-4 w-4" /> Tambah {props.entity === "products" ? "Produk" : "Kategori"}</button>}</div><div className="grid gap-3 border-b border-black/10 p-5 md:grid-cols-[1fr_15rem]"><div className="relative"><label className="sr-only" htmlFor={`${props.entity}-search`}>Cari</label><input id={`${props.entity}-search`} value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} className="form-input pl-11" placeholder={settings.search} /><Icon name="search" className="pointer-events-none absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2" /></div><select className="form-input" value={filter} onChange={(event) => { setFilter(event.target.value); setPage(1); }} aria-label="Filter tabel">{filters.map((item) => <option key={item}>{item}</option>)}</select></div><div className="px-5 py-4 text-sm"><strong className="text-ink-black">{filtered.length}</strong> data ditemukan</div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-ink-black text-xs uppercase tracking-[0.12em] text-white"><tr>{headers.map((header) => <th key={header} className="px-4 py-3">{header}</th>)}</tr></thead><tbody>
    {props.entity === "products" && (rows as ProductRow[]).map((row) => <tr key={row.id} className="border-b border-black/8"><td className="px-4 py-4"><div className="flex items-center gap-3">{row.imageUrl ? <Image src={row.imageUrl} alt={row.imageAlt} width={48} height={48} className="h-12 w-12 rounded-lg object-cover" /> : <span className="h-12 w-12 rounded-lg bg-canvas-gray" />}<div><p className="font-bold text-ink-black">{row.name}</p><p className="text-xs">{row.slug}</p></div></div></td><td className="px-4 py-4">{row.category}</td><td className="px-4 py-4">{formatCurrency(row.price)}</td><td className="px-4 py-4">{row.stock}</td><td className="px-4 py-4">{row.isActive ? "Aktif" : "Nonaktif"}</td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={() => setEditor({ kind: "product", row })} className="rounded-lg border border-black/15 p-2" aria-label={`Edit ${row.name}`}><Icon name="edit" /></button><button disabled={busy === row.id} onClick={() => remove(row.id)} className="rounded-lg border border-status-error/25 p-2 text-status-error" aria-label={`Hapus ${row.name}`}><Icon name="trash" /></button></div></td></tr>)}
    {props.entity === "categories" && (rows as CategoryRow[]).map((row) => <tr key={row.id} className="border-b border-black/8"><td className="px-4 py-4 font-bold text-ink-black">{row.name}</td><td className="px-4 py-4">{row.slug}</td><td className="px-4 py-4">{row.productCount}</td><td className="px-4 py-4">{formatDate(row.createdAt)}</td><td className="px-4 py-4">{row.isActive ? "Aktif" : "Nonaktif"}</td><td className="px-4 py-4"><div className="flex gap-2"><button onClick={() => setEditor({ kind: "category", row })} className="rounded-lg border border-black/15 p-2" aria-label={`Edit ${row.name}`}><Icon name="edit" /></button><button disabled={busy === row.id} onClick={() => remove(row.id)} className="rounded-lg border border-status-error/25 p-2 text-status-error" aria-label={`Hapus ${row.name}`}><Icon name="trash" /></button></div></td></tr>)}
    {props.entity === "orders" && (rows as OrderRow[]).map((row) => <tr key={row.id} className="border-b border-black/8"><td className="px-4 py-4 font-bold text-ink-black">{row.id}</td><td className="px-4 py-4">{row.customer}</td><td className="px-4 py-4">{formatDate(row.date)}</td><td className="px-4 py-4">{formatCurrency(row.total)}</td><td className="px-4 py-4"><StatusBadge status={row.status} /></td><td className="px-4 py-4"><div className="flex gap-2"><select disabled={busy === row.id} className="rounded-lg border border-black/15 p-2 text-xs" defaultValue="" onChange={(event) => event.target.value && updateStatus(row.id, event.target.value)} aria-label={`Ubah status ${row.id}`}><option value="" disabled>Update</option><option>PROCESSING</option><option>SHIPPED</option><option>COMPLETED</option></select><button disabled={busy === row.id} onClick={() => remove(row.id)} className="rounded-lg border border-status-error/25 p-2 text-status-error" aria-label={`Arsipkan ${row.id}`}><Icon name="trash" /></button></div></td></tr>)}
    {!rows.length && <tr><td colSpan={6} className="px-5 py-12 text-center">Tidak ada data yang cocok.</td></tr>}
  </tbody></table></div><nav className="flex items-center justify-between border-t border-black/10 px-5 py-4" aria-label="Pagination tabel"><p className="text-sm">Halaman {safePage} dari {totalPages}</p><div className="flex gap-2"><button className="btn-secondary px-4 py-2 text-sm" disabled={safePage <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))}>Sebelumnya</button><button className="btn-secondary px-4 py-2 text-sm" disabled={safePage >= totalPages} onClick={() => setPage((value) => Math.min(totalPages, value + 1))}>Berikutnya</button></div></nav></section>
  {editor && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/60 p-4" role="dialog" aria-modal="true" aria-labelledby="editor-title" onMouseDown={(event) => event.target === event.currentTarget && setEditor(null)}><div className="max-h-[90vh] w-full max-w-xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl sm:p-8"><div className="flex items-start justify-between border-b-2 border-brand-yellow pb-4"><div><p className="text-xs font-bold uppercase tracking-[0.16em]">Form Admin</p><h2 id="editor-title" className="font-display text-3xl font-bold text-ink-black">{editor.row ? "Edit" : "Tambah"} {editor.kind === "product" ? "Produk" : "Kategori"}</h2></div><button type="button" className="rounded-full p-2" onClick={() => setEditor(null)} aria-label="Tutup modal"><Icon name="close" /></button></div><form className="mt-6 space-y-5" onSubmit={saveEditor}><div><label className="form-label" htmlFor="editor-name">Nama</label><input id="editor-name" name="name" className="form-input" defaultValue={editor.row?.name ?? ""} required /></div>
    {editor.kind === "product" && props.entity === "products" && <><div className="grid gap-5 sm:grid-cols-2"><div><label className="form-label" htmlFor="editor-category">Kategori</label><select id="editor-category" name="categoryId" className="form-input" defaultValue={editor.row?.categoryId ?? props.categories[0]?.id} required>{props.categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></div><div><label className="form-label" htmlFor="editor-price">Harga</label><input id="editor-price" name="price" type="number" min="0" className="form-input" defaultValue={editor.row?.price ?? 0} required /></div></div><div className="grid gap-5 sm:grid-cols-2"><div><label className="form-label" htmlFor="editor-stock">Stok</label><input id="editor-stock" name="stock" type="number" min="0" className="form-input" defaultValue={editor.row?.stock ?? 0} required /></div><div><label className="form-label" htmlFor="editor-badge">Badge</label><input id="editor-badge" name="badge" className="form-input" defaultValue={editor.row?.badge ?? ""} /></div></div><div><label className="form-label" htmlFor="editor-description">Deskripsi</label><textarea id="editor-description" name="description" className="form-input min-h-28" defaultValue={editor.row?.description ?? ""} required /></div><div><label className="form-label" htmlFor="editor-keywords">Keywords (pisahkan koma)</label><input id="editor-keywords" name="keywords" className="form-input" defaultValue={editor.row?.keywords.join(", ") ?? ""} /></div><div><label className="form-label" htmlFor="editor-image">URL gambar Cloudinary/Unsplash</label><input id="editor-image" name="imageUrl" type="url" className="form-input" defaultValue={editor.row?.imageUrl ?? ""} required /></div><div><label className="form-label" htmlFor="editor-alt">Alt gambar</label><input id="editor-alt" name="imageAlt" className="form-input" defaultValue={editor.row?.imageAlt ?? ""} required /></div><label className="flex items-center gap-3 text-sm font-bold"><input type="checkbox" name="featured" defaultChecked={editor.row?.featured} className="h-4 w-4 accent-brand-yellow" /> Produk unggulan</label></>}
    <div><label className="form-label" htmlFor="editor-status">Status</label><select id="editor-status" name="isActive" className="form-input" defaultValue={editor.row?.isActive === false ? "false" : "true"}><option value="true">Aktif</option><option value="false">Nonaktif</option></select></div>{formError && <p className="form-error" role="alert">{formError}</p>}<div className="flex justify-end gap-3 border-t border-black/10 pt-5"><button type="button" className="btn-secondary px-5 py-2.5" onClick={() => setEditor(null)}>Batal</button><button disabled={busy === "editor"} className="btn-primary px-5 py-2.5 disabled:opacity-60">{busy === "editor" ? "Menyimpan…" : "Simpan"}</button></div></form></div></div>}
  </>;
}
