"use client";

import { useState, type FormEvent } from "react";
import { Icon } from "../ui/Icon";
import { useToast } from "../ui/ToastProvider";

interface Profile { name: string; email: string; phone?: string | null; address?: string | null; city?: string | null; postalCode?: string | null }
export function ProfileForm({ profile }: { profile: Profile }) {
  const { showToast } = useToast(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  const initials = profile.name.split(/\s+/).slice(0, 2).map((part) => part[0]).join("").toUpperCase();
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!event.currentTarget.reportValidity()) return; setSaving(true); setError(""); const values = new FormData(event.currentTarget); const response = await fetch("/api/profile", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ name: values.get("name"), phone: values.get("phone"), address: values.get("address"), city: values.get("city"), postalCode: values.get("postalCode") }) }); const result = await response.json() as { error?: string }; setSaving(false); if (!response.ok) return setError(result.error ?? "Profil belum dapat disimpan."); showToast("Profil berhasil diperbarui."); };
  return <article className="rounded-2xl bg-white p-6 shadow-sm sm:p-8"><div className="flex flex-col gap-5 border-b border-black/10 pb-6 sm:flex-row sm:items-center"><span className="grid h-24 w-24 shrink-0 place-items-center rounded-full bg-brand-yellow font-display text-4xl font-extrabold text-ink-black" aria-hidden="true">{initials}</span><div><p className="text-xs font-bold uppercase tracking-[0.16em]">Member KreasiKita</p><h2 className="font-display text-3xl font-bold text-ink-black">{profile.name}</h2><p className="mt-1 text-sm">{profile.email}</p></div></div><form className="mt-7 space-y-6" onSubmit={submit}><div className="grid gap-5 sm:grid-cols-2"><div><label className="form-label" htmlFor="profile-name">Nama lengkap</label><input id="profile-name" name="name" className="form-input" defaultValue={profile.name} required /></div><div><label className="form-label" htmlFor="profile-email">Email</label><input id="profile-email" className="form-input bg-canvas-gray/60" defaultValue={profile.email} disabled /></div><div><label className="form-label" htmlFor="profile-phone">Nomor telepon</label><input id="profile-phone" name="phone" className="form-input" defaultValue={profile.phone ?? ""} /></div><div><label className="form-label" htmlFor="profile-city">Kota</label><input id="profile-city" name="city" className="form-input" defaultValue={profile.city ?? ""} /></div><div><label className="form-label" htmlFor="profile-postal">Kode pos</label><input id="profile-postal" name="postalCode" className="form-input" defaultValue={profile.postalCode ?? ""} /></div></div><div><label className="form-label" htmlFor="profile-address">Alamat utama</label><textarea id="profile-address" name="address" className="form-input min-h-28" defaultValue={profile.address ?? ""} /></div>{error && <p className="form-error" role="alert">{error}</p>}<div className="flex justify-end border-t border-black/10 pt-6"><button disabled={saving} className="btn-primary px-6 py-3 disabled:opacity-60">{saving ? "Menyimpan…" : "Simpan Perubahan"}</button></div><p className="flex items-center gap-2 text-xs"><Icon name="shield" className="h-4 w-4 text-status-success" /> Data profil hanya dapat diubah oleh akun yang sedang masuk.</p></form></article>;
}
